language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
script:
  - nyc npm test
  - npm run build
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: kU6FIT06bOAMeAQxTXYgmj6pKNq+gQpzhEh4jv48AZj9DxjFxhKhKEe4ucUyLJdJW9htdd5T9vIj5VRjZz+MSTgXwQYPDXznEpZUS+aWVxIhXn2mR+92uj3Iedz7d8wu2/O5OssThM4XbcqYlWQrdetJGZ7E75kUbACauS0ltWM3i8L2+PraLj19oCtC24qqE70GD+RUQLKqSYYnrmZLsIdJdZbPrappPffhcjsht23CE5rbYk3N2Zsa4sz5kDxzGr8QX/bQ4qRByAQc4cRj3STVNl3nC8p58jHQUIV2fwQZZXRk4e5sOmt5khzkfBu4ZMHej0EYlQOVtZZBttMvQgvWG1c39YQAU3glrAtzTX9oNRFBuPGWUqFROeol3Lf5e6i0TzHGafEn/OycRlT7HNlZ2A+Fx+ikhgqNcekpVO1iu8iic90hxo73dGQ3RWyXMrZ+GlZWEmwkLPjZy2KwNmH4tMXFSJvlEmswe5HoNLVixWn8gFykNdUd6eG5yQTg/qmsftmTcV7yDxiz5Pkb1nbo89xPy8EZcLDrRE0dEfZCkLAJJ1gJ8ToSIAoTx6aYDOOIWhDFsPO1Eri9I22O7fWoPW2XBTqhh94Q1r8A4XOBik8/51w2KWtFqgwYKhawK0J7F9SGh7Vx2KY4Iiqjdwcw6aNEznp/FBeCjWbt/bw=
  skip_cleanup: true
  on:
    tags: true
    node: 5
